# Action that wraps together all the necessary actions to build an image and publish it.
# It does not include login actions.
# This is a convenience, so that we know that everything related to the build lies in this file,
# and if it gets updated we can automatically run our `test-docker-build` from `build-test.yml.`,
# so there is no confusion about which is the job that was updated, if there are many in the same workflow file.

name: "Docker Build"
description: "Builds Docker images with optional caching and multi-platform support"

inputs:
  push:
    description: "Whether to push the built image"
    required: false
    default: "false"
  load:
    description: "Whether to load the built image"
    required: false
    default: "false"
  platforms:
    description: "Target platforms for the build"
    required: false
    default: "linux/amd64"
  dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "./Dockerfile"
  context:
    description: "Build context path"
    required: false
    default: "."
  image-name:
    description: "Docker image name"
    required: true
  cache-from:
    description: "Cache source for Docker build"
    required: false
    default: ""
  cache-to:
    description: "Cache destination for Docker build"
    required: false
    default: ""
  setup-qemu:
    description: "Whether to set up QEMU for multi-platform builds"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false

    - name: Set up QEMU
      if: inputs.setup-qemu == 'true'
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: ${{ inputs['image-name'] }}
        tags: |
          type=semver,enable=true,pattern={{raw}}
          type=semver,enable=true,pattern={{major}},prefix=v
          type=ref,event=pr,prefix=pr-,enable=true
          type=ref,event=branch,branch=main,pattern={{raw}}
          type=ref,event=branch,branch=main,pattern={{major}},prefix=v

    - name: Build Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: ${{ inputs['cache-from'] }}
        cache-to: ${{ inputs['cache-to'] }}
        load: ${{ inputs.load }}
