# Action that wraps together all the necessary actions to build an image and publish it.
# It does not include login actions.
# This is a convenience, so that we know that everything related to the build lies in this file,
# and if it gets updated we can automatically run our `test-docker-build` from `build-test.yml.`

name: "Docker Build"
description: "Builds Docker images with optional caching and multi-platform support"

inputs:
  push-image:
    description: "Whether to push the built image"
    required: false
    default: "false"
  platforms:
    description: "Target platforms for the build"
    required: false
    default: "linux/amd64"
  dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "./Dockerfile"
  context:
    description: "Build context path"
    required: false
    default: "."
  image-name:
    description: "Docker image name"
    required: true
  cache-from:
    description: "Cache source for Docker build"
    required: false
    default: ""
  cache-to:
    description: "Cache destination for Docker build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: ${{ inputs['image-name'] }}

    - name: Build Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs['push-image'] }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: ${{ inputs['cache-from'] }}
        cache-to: ${{ inputs['cache-to'] }}
