name: Build and Test Docker Image

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        required: true
      platform:
        type: string
        required: false
        default: "linux/amd64"
      image-name:
        type: string
        required: true
      cache-from:
        type: string
        required: false
        default: ""
      cache-to:
        type: string
        required: false
        default: ""
      setup-qemu:
        type: string
        required: false
        default: "false"

jobs:
  test-docker-build:
    name: Test Docker build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: ./.github/actions/docker-build
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          platforms: ${{ inputs.platform }}
          cache-from: ${{ inputs.cache-from }}
          cache-to: ${{ inputs.cache-to }}
          image-name: ${{ inputs.image-name }}
          setup-qemu: ${{ inputs.setup-qemu }}

      - name: Test
        run: |
          docker run --platform ${{ inputs.platform }} --rm ${{ inputs.image-name }}:${{ inputs.image-tag }} --version
