name: Test Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/twyn
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"
      - name: Publish to PyPi
        run: |
          uv build
          uv publish
